export const SampleMovie = {
    adult: false,
    backdrop_path: "/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg",
    belongs_to_collection: {
        id: 10,
        name: "Star Wars Collection",
        poster_path: "/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg",
        backdrop_path: "/d8duYyyC9J5T825Hg7grmaabfxQ.jpg",
    },
    budget: 200000000,
    genres: [
        {
            id: 14,
            name: "Fantasy",
        },
        {
            id: 12,
            name: "Adventure",
        },
        {
            id: 878,
            name: "Science Fiction",
        },
        {
            id: 28,
            name: "Action",
        },
    ],
    homepage: "https://www.starwars.com/films/star-wars-episode-viii-the-last-jedi",
    id: 181808,
    imdb_id: "tt2527336",
    original_language: "en",
    original_title: "Star Wars: The Last Jedi",
    overview:
        "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.",
    popularity: 44.208,
    poster_path: "/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
    production_companies: [
        {
            id: 1,
            logo_path: "/o86DbpburjxrqAzEDhXZcyE8pDb.png",
            name: "Lucasfilm",
            origin_country: "US",
        },
        {
            id: 11092,
            logo_path: null,
            name: "Ram Bergman Productions",
            origin_country: "US",
        },
        {
            id: 2,
            logo_path: "/wdrCwmRnLFJhEoH8GSfymY85KHT.png",
            name: "Walt Disney Pictures",
            origin_country: "US",
        },
    ],
    production_countries: [
        {
            iso_3166_1: "US",
            name: "United States of America",
        },
    ],
    release_date: "2017-12-13",
    revenue: 1332459537,
    runtime: 152,
    spoken_languages: [
        {
            iso_639_1: "en",
            name: "English",
        },
    ],
    status: "Released",
    tagline: "Darkness rises... and light to meet it",
    title: "Star Wars: The Last Jedi",
    video: false,
    vote_average: 7,
    vote_count: 9692,
};

export const SampleCredits = {
    id: 436969,
    cast: [
        {
            adult: false,
            gender: 1,
            id: 234352,
            known_for_department: "Acting",
            name: "Margot Robbie",
            original_name: "Margot Robbie",
            popularity: 51.193,
            profile_path: "/euDPyqLnuwaWMHajcU3oZ9uZezR.jpg",
            cast_id: 33,
            character: "Harleen Quinzel / Harley Quinn",
            credit_id: "5ca268419251411a16098d23",
            order: 0,
        },
        {
            adult: false,
            gender: 2,
            id: 16483,
            known_for_department: "Acting",
            name: "Sylvester Stallone",
            original_name: "Sylvester Stallone",
            popularity: 37.297,
            profile_path: "/qDRGPAcQoW8Wuig9bvoLpHwf1gU.jpg",
            cast_id: 75,
            character: "Nanaue / King Shark (voice)",
            credit_id: "5fb089986dc6c000422ab02a",
            order: 4,
        },
        {
            adult: false,
            gender: 1,
            id: 1784612,
            known_for_department: "Acting",
            name: "Daniela Melchior",
            original_name: "Daniela Melchior",
            popularity: 29.324,
            profile_path: "/ieINP7YlragZ999aU0zfuve1lM2.jpg",
            cast_id: 41,
            character: "Cleo Cazo / Ratcatcher 2",
            credit_id: "5ccafd480e0a262fb3ff4237",
            order: 7,
        },
    ],
    crew: [
        {
            adult: false,
            gender: 0,
            id: 282,
            known_for_department: "Production",
            name: "Charles Roven",
            original_name: "Charles Roven",
            popularity: 2.124,
            profile_path: "/4uJLoVstC1CBcArXFOe53N2fDr1.jpg",
            credit_id: "5a584b3cc3a3681eb2003de9",
            department: "Production",
            job: "Producer",
        },
        {
            adult: false,
            gender: 2,
            id: 960,
            known_for_department: "Sound",
            name: "John Murphy",
            original_name: "John Murphy",
            popularity: 0.6,
            profile_path: "/zjCRjbBQ8zoaKwka9iS7zbmBrTr.jpg",
            credit_id: "5f2cbf99afe2240034fc1630",
            department: "Sound",
            job: "Original Music Composer",
        },
        {
            adult: false,
            gender: 2,
            id: 900,
            known_for_department: "Sound",
            name: "Christopher Boyes",
            original_name: "Christopher Boyes",
            popularity: 3.347,
            profile_path: null,
            credit_id: "60f28cd2d35dea00264f8ed6",
            department: "Sound",
            job: "Sound Re-Recording Mixer",
        },
    ],
};

export const SampleActor = {
    adult: false,
    also_known_as: [
        "Марго Роббі",
        "Марго Робби",
        "มาร์โก ร็อบบี",
        "瑪歌·羅比",
        "마고 로비",
        "مارجوت روبي",
        "マーゴット・ロビー",
        "Марго Роби",
        "Margot Elise Robbie",
        "Μάργκοτ Ελίς Ρόμπι",
        "Μάργκοτ Ρόμπι",
        "玛格特·罗比",
        "Марґо Роббі",
    ],
    biography:
        "Margot Elise Robbie (born 2 July 1990) is an Australian actress and producer. She has received nominations for two Academy Awards and five BAFTA Awards. In 2017, Time magazine named her one of the 100 most influential people in the world, and in 2019, she was ranked among the world's highest-paid actresses.\n\nRobbie studied drama at Somerset College and began her career in Australian independent films in the late 2000s, before working in the soap opera Neighbours (2008–2011). After moving to America, she starred in the ABC drama series Pan Am (2011–2012) and had her breakthrough role in Martin Scorsese's black comedy film The Wolf of Wall Street (2013). Robbie's profile continued to grow with starring roles as a grifter in Focus (2015), Jane Porter in The Legend of Tarzan (2016), and Harley Quinn in the DC Extended Universe, beginning with Suicide Squad (2016).\n\nRobbie garnered critical acclaim and nominations for the BAFTA Award and Academy Award for Best Actress for portraying the disgraced figure skater Tonya Harding in the biopic I, Tonya (2017). This acclaim continued for her roles as Queen Elizabeth I in the period drama Mary Queen of Scots (2018), Sharon Tate in the comedy-drama Once Upon a Time in Hollywood (2019), and a fictional Fox News employee in the drama Bombshell (2019). She received BAFTA Award nominations for all three and a nomination for the Academy Award for Best Supporting Actress for the lattermost.\n\nRobbie is married to the filmmaker Tom Ackerley. They are among the founders of the production company LuckyChap Entertainment, under which she has produced some of her own films, as well as the television series Dollface (2019–present).",
    birthday: "1990-07-02",
    deathday: null,
    gender: 1,
    homepage: null,
    id: 234352,
    imdb_id: "nm3053338",
    known_for_department: "Acting",
    name: "Margot Robbie",
    place_of_birth: "Dalby, Queensland, Australia",
    popularity: 51.193,
    profile_path: "/euDPyqLnuwaWMHajcU3oZ9uZezR.jpg",
};

export const SampleReview = {
    author: "Peter89Spencer",
    author_details: {
        name: "",
        username: "Peter89Spencer",
        avatar_path: "/https://secure.gravatar.com/avatar/dadb1b759a8516c815cdcc58abcefc85.jpg",
        rating: 8,
    },
    content:
        "The Suicide Squad...\r\n...stayed true to the hype of the anti-hero teams in DC.\r\n\r\nI feel like it wasn't really a sequel but rather a reboot and ignoring the first film.\r\nThe action was insane and BLOODY brilliant, with a stellar cast. And they LITERALLY killed off the first team at the very start of the film! To be honest, I wasn't really surprised as I didn't see more of them in later scenes of the trailer. But I was surprised they killed off Captain Boomerang - he was basically the primary member of the team! And I especially wanted to see more character build up with Savant, learn more of his backstory. Instead, he just turned out to be a totally wuss that's only good at killing small birds! But what shocked me the most was Rick Flagg's death!\r\n\r\nStill, Idris Elba and John Cena were fucking awesome as Bloodsport and Peacemaker, respectively. And King Shark was hilariously awesome. Funnier that Groot because at least he says more than three words - although, \"hand\" would have to be my favourite moment!\r\n\r\nI did had mixed feelings from the start, but then I started to really get into it all!",
    created_at: "2021-07-30T23:37:33.102Z",
    id: "61048d3d688cd0007f215a28",
    updated_at: "2021-07-30T23:37:33.102Z",
    url: "https://www.themoviedb.org/review/61048d3d688cd0007f215a28",
};

export const SampleSearchProps = {
    searchQuery: "test",
    history: {
        length: 2,
        action: "PUSH",
        location: {
            pathname: "/search",
            search: "",
            hash: "",
            key: "fxki1m",
        },
    },
    location: {
        pathname: "/search",
        search: "",
        hash: "",
        key: "fxki1m",
    },
    match: {
        path: "/search",
        url: "/search",
        isExact: true,
        params: {},
    },
};
